version: 2
jobs:
  build:
    macos:
      xcode: "11.3.0"

    working_directory: ~/repo

    steps:
      - checkout

      # Set up environment
      - run: npm install -g react-native-cli
      - run: npm install -g detox-cli
      - run: brew tap wix/brew
      - run: brew install applesimutils

      # run Snapshot Testing tests
       - run: npm install
      - run: npm run lint
