name: Build test
on:
  push:
    branches:
      - New-Test-Branch
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run Linters
        run: |
          npm run lint
      - name: Snapshot Testing
        run: |
          npm run test
